services:
  web:
    image: docker.jashom.com/jashom-web:${TAG}
    container_name: jashom-web
    read_only: true

    tmpfs:
      - /tmp/nginx:uid=1000,gid=1000,mode=755
      - /var/run

    ports:
      - "2128:80"

    restart: unless-stopped

