services:
  web:
    image: docker.jashom.com/jashom-web:${TAG}
    container_name: jashom-web

    read_only: true

    tmpfs:
      - /var/cache/nginx
      - /var/run

    ports:
      - "2128:80"

    restart: unless-stopped

