services:
  web:
    image: docker.jashom.com/jashom-web:${TAG}
    container_name: jashom-web

    read_only: true

    tmpfs:
      - /var/cache/nginx:uid=1000,gid=1000,mode=0755
      - /var/run:uid=1000,gid=1000,mode=0755

    ports:
      - "2128:80"

    restart: unless-stopped

